export const Languages = [
  "Arabic",
  "Czech",
  "Danish",
  "German",
  "Greek",
  "English",
  "Spanish",
  "Finnish",
  "French",
  "Hebrew",
  "Hungarian",
  "Italian",
  "Japanese",
  "Korean",
  "Norwegian",
  "Dutch",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Slovak",
  "Slovenian",
  "Swedish",
  "Turkish",
  "Ukrainian",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
];